name: Deploy Github Pages

on:
  # 每当 push 到 master 分支时触发部署
  push:
    branchs: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '14'

      # 运行构建脚本
      - name: Build
        run: npm install && npm run docs:build

      - name: Depoly to Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with: 
          # 部署到 gh-page 分支
          target_branch: gh-pages
          # 部署目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
